package calculadora2;


import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Celso
 */
public class Cliente extends javax.swing.JFrame{
   boolean a=false;
   float numero;
   String operacion;
    /**
     * Creates new form Clientetest
     */
    public Cliente() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bton1 = new javax.swing.JButton();
        bton2 = new javax.swing.JButton();
        bton3 = new javax.swing.JButton();
        bton4 = new javax.swing.JButton();
        bton5 = new javax.swing.JButton();
        bton6 = new javax.swing.JButton();
        bton7 = new javax.swing.JButton();
        bton8 = new javax.swing.JButton();
        bton9 = new javax.swing.JButton();
        btonX = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        btonsum = new javax.swing.JButton();
        Porcen = new javax.swing.JButton();
        btnrest = new javax.swing.JButton();
        Switch = new javax.swing.JButton();
        Pantalla = new javax.swing.JTextField();
        btnfin = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btncoma = new javax.swing.JButton();
        btnegativo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bton1.setText("1");
        bton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton1ActionPerformed(evt);
            }
        });

        bton2.setText("2");
        bton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton2ActionPerformed(evt);
            }
        });

        bton3.setText("3");
        bton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton3ActionPerformed(evt);
            }
        });

        bton4.setText("4");
        bton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton4ActionPerformed(evt);
            }
        });

        bton5.setText("5");
        bton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton5ActionPerformed(evt);
            }
        });

        bton6.setText("6");
        bton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton6ActionPerformed(evt);
            }
        });

        bton7.setText("7");
        bton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton7ActionPerformed(evt);
            }
        });

        bton8.setText("8");
        bton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton8ActionPerformed(evt);
            }
        });

        bton9.setText("9");
        bton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton9ActionPerformed(evt);
            }
        });

        btonX.setText("X");
        btonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonXActionPerformed(evt);
            }
        });

        btndiv.setText("/");
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivActionPerformed(evt);
            }
        });

        btonsum.setText("+");
        btonsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonsumActionPerformed(evt);
            }
        });

        Porcen.setText("%");
        Porcen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorcenActionPerformed(evt);
            }
        });

        btnrest.setText("-");
        btnrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestActionPerformed(evt);
            }
        });

        Switch.setText("On");
        Switch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwitchActionPerformed(evt);
            }
        });

        Pantalla.setEnabled(false);
        Pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaActionPerformed(evt);
            }
        });

        btnfin.setText("=");
        btnfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinActionPerformed(evt);
            }
        });

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btncoma.setText(".");
        btncoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomaActionPerformed(evt);
            }
        });

        btnegativo.setText("--");
        btnegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnegativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnclear)
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Porcen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnegativo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(bton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(bton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(bton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bton5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .addComponent(bton2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .addComponent(bton8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                                        .addGap(22, 22, 22)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btonsum, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btncoma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btonX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Switch)
                                .addGap(67, 67, 67)
                                .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnfin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnrest)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(308, Short.MAX_VALUE)
                    .addComponent(btndiv)
                    .addGap(53, 53, 53)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Switch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btonX, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bton3)
                            .addComponent(bton2)
                            .addComponent(bton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bton4)
                            .addComponent(bton5)
                            .addComponent(bton6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bton8)
                            .addComponent(bton9)
                            .addComponent(bton7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnegativo))
                    .addComponent(btncoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btonsum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Porcen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnrest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnfin)
                        .addGap(18, 18, 18)
                        .addComponent(btnclear)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(172, Short.MAX_VALUE)
                    .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(103, 103, 103)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton2ActionPerformed
       Pantalla.setText(Pantalla.getText()+"2");
    }//GEN-LAST:event_bton2ActionPerformed

    private void bton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton3ActionPerformed
       Pantalla.setText(Pantalla.getText()+"3");
    }//GEN-LAST:event_bton3ActionPerformed

    private void bton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton4ActionPerformed
        Pantalla.setText(Pantalla.getText()+"4");
    }//GEN-LAST:event_bton4ActionPerformed

    private void bton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton1ActionPerformed
       Pantalla.setText(Pantalla.getText()+"1");
    }//GEN-LAST:event_bton1ActionPerformed

    private void bton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton5ActionPerformed
        Pantalla.setText(Pantalla.getText()+"5");
    }//GEN-LAST:event_bton5ActionPerformed

    private void bton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton6ActionPerformed
       Pantalla.setText(Pantalla.getText()+"6");
    }//GEN-LAST:event_bton6ActionPerformed

    private void bton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton8ActionPerformed
        Pantalla.setText(Pantalla.getText()+"8");
    }//GEN-LAST:event_bton8ActionPerformed

    private void bton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton9ActionPerformed
       Pantalla.setText(Pantalla.getText()+"9");
    }//GEN-LAST:event_bton9ActionPerformed

    private void btonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonXActionPerformed
        numero=Float.parseFloat(Pantalla.getText());
        operacion="X";
        Pantalla.setText("");
    }//GEN-LAST:event_btonXActionPerformed

    private void bton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton7ActionPerformed
       Pantalla.setText(Pantalla.getText()+"7");
    }//GEN-LAST:event_bton7ActionPerformed

    private void btonsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonsumActionPerformed
        numero=Float.parseFloat(Pantalla.getText());
        operacion="+";
        Pantalla.setText("");
    }//GEN-LAST:event_btonsumActionPerformed

    private void PorcenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorcenActionPerformed
         numero=Float.parseFloat(Pantalla.getText());
        operacion="%";
        Pantalla.setText("");
    }//GEN-LAST:event_PorcenActionPerformed

    private void btnrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestActionPerformed
          numero=Float.parseFloat(Pantalla.getText());
        operacion="-";
        Pantalla.setText("");
    }//GEN-LAST:event_btnrestActionPerformed

    private void btndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivActionPerformed
         numero=Float.parseFloat(Pantalla.getText());
        operacion="/";
        Pantalla.setText("");
    }//GEN-LAST:event_btndivActionPerformed

    private void SwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwitchActionPerformed
        a=!a;
        if(Switch.getText().contains("Off")){
            Switch.setText("On");
        }else{
            Switch.setText("Off");
        }
    }//GEN-LAST:event_SwitchActionPerformed

    private void PantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaActionPerformed

    private void btnfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinActionPerformed
       try {
           String resultado;
           String algo=Pantalla.getText();
           Socket socket= new Socket();
           InetSocketAddress aert= new InetSocketAddress("localhost",5555);
           socket.connect(aert);
           DataInputStream llegada= new DataInputStream(socket.getInputStream());
           DataOutputStream salida= new DataOutputStream(socket.getOutputStream());
           salida.writeFloat(numero);
           salida.writeUTF(operacion);
           
           float numero2=Float.parseFloat(algo);           
           salida.writeFloat(numero2);
           resultado=llegada.readUTF();
           Pantalla.setText(resultado);
           socket.close();
       } catch (IOException ex) {
           Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnfinActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        Pantalla.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btncomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomaActionPerformed
       Pantalla.setText(Pantalla.getText()+".");
    }//GEN-LAST:event_btncomaActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        Pantalla.setText(Pantalla.getText()+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnegativoActionPerformed
       float negativo=Float.parseFloat(Pantalla.getText());
       negativo=-negativo;
       Pantalla.setText(negativo+"");
    }//GEN-LAST:event_btnegativoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Cliente test= new Cliente();
     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Cliente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Pantalla;
    private javax.swing.JButton Porcen;
    private javax.swing.JButton Switch;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btncoma;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btnegativo;
    private javax.swing.JButton btnfin;
    private javax.swing.JButton btnrest;
    private javax.swing.JButton bton1;
    private javax.swing.JButton bton2;
    private javax.swing.JButton bton3;
    private javax.swing.JButton bton4;
    private javax.swing.JButton bton5;
    private javax.swing.JButton bton6;
    private javax.swing.JButton bton7;
    private javax.swing.JButton bton8;
    private javax.swing.JButton bton9;
    private javax.swing.JButton btonX;
    private javax.swing.JButton btonsum;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

   
}
